#%RAML 1.0 Trait

headers:
  transactionid:
    required: true
    type: string
    minLength: 36
    maxLength: 36
    example: "12345-45678-34567-78956-23789-456785"
  clientid:
    required: true
    type: string
    example: "abnvchfurtkgvnmdn"
  clientsecret:
    required: true
    type: string
    example: "anfghtsjfutznxhfhnfv"
